server:
  port: 9191
  context-path: /liquibase

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liquibase_db?nullNamePatternMatchesAll=true&useSSL=false
    datasourceClassName: com.mysql.cj.jdbc.MysqlDataSource

    username: liquibase_user
    password: password